# JSC, Julich Supercomputing Centre: Jureca + SBATCH
host_name: "Jureca"
host_login: "kay.ichec.ie"
host_location: "JSC, Julich Supercomputing Centre"
host_homedir: "/ichec/home/course01"  # watch out due to course accounts
host_prompt: "[user@laptop ~]$"
sched_name: "SBATCH" # Check
sched_submit: "sbatch"
sched_submit_options: "-A course01" # check
sched_status: "sstat"
sched_flag_user: "-u yourUsername"
sched_flag_time: "--time "
sched_flag_node: "--nodes "
sched_del: "scancel"
sched_interactive: "sbatch"
sched_comment: "#SBATCH"
sched_flag_name: "-N" # EDITME
sched_hist: "" # EDITME
sched_flag_histdetail: "" # EDITME 
module_lammps: "module load LAMMPS/9Jan2020-cuda"
module_intel: "module load intel-para/2019a"
module_devel: "module load Stages/Devel-2019a"
module_usage: "module use /usr/local/software/jureca/OtherStages"
run_openmp: "srun"
run_mpi: ""


