#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", "lc", or "cp")?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor traning for instance)
carpentry: "swc"

# Overall title for pages.
title: "Running LAMMPS on HPC systems"

# Email address, no mailto:
email: "a.ocais@fz-juelich.de"

# Life cycle stage of the lesson
# possible values: "pre-alpha", "alpha", "beta", "stable"
life_cycle: "alpha"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Magic to make URLs resolve both locally and on GitHub. Please don't change.
repository: <USERNAME>/<PROJECT>

# Invoke the Carpentries theme rather than copying into our repository.
remote_theme: carpentries/carpentries-theme

# Sites.
amy_site: "https://amy.software-carpentry.org/workshops"
dc_site: "http://datacarpentry.org"
swc_github: "https://github.com/swcarpentry"
swc_site: "https://software-carpentry.org"
swc_pages: "https://swcarpentry.github.io"
lc_site: "http://librarycarpentry.github.io/"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"
workshop_repo: "https://github.com/swcarpentry/workshop-template"
workshop_site: "https://swcarpentry.github.io/workshop-template"
training_site: "https://swcarpentry.github.io/instructor-training"

# Specify that things in the Episodes and Extras collections should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html
# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page
# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
# Turn on built-in syntax highlighting.
highlighter: rouge


# Workshop Specific Values
##########################
# SITE Specific configuration
# Host and scheduler options
#
# Other options can be found in _extras/snippets_library

host_name: "Jureca"
#host_login: "kay.ichec.ie"
host_location: "JSC, Julich Supercomputing Centre"
#host_homedir: "/ichec/home/course01"  # watch out due to course accounts
host_prompt: "[user@laptop ~]$"
sched_name: SLURM
sched_submit: "sbatch"
sched_submit_options: "-A course01" # check
sched_flag_account: "--account"
sched_flag_time: "--time "
sched_flag_nodes: "--nodes "
sched_flag_ntasks: "--ntasks-per-node"
sched_flag_out: "--output"
sched_flag_err: "--error"
sched_flag_partition: "--partition"
sched_status: "sstat"
sched_flag_user: "-u yourUsername"
sched_queue: "batch"
sched_del: "scancel"
sched_interactive: "srun --pty /bin/bash -i"
sched_comment: "#SBATCH"
sched_flag_name: "-N" # EDITME
sched_hist: "" # EDITME
sched_flag_histdetail: "" # EDITME
mpi_runtime_single_core_flags: "-n 1"
lammps_version: "LAMMPS/9Jan2020-cuda"
lammps_exec: lmp
kokkos_env: "module use /usr/local/software/jureca/OtherStages \nmodule load Stages/Devel-2019a intel-para/2019a LAMMPS/9Jan2020-kokkos"
gpu_env: "module use /usr/local/software/jureca/OtherStages \nmodule load Stages/Devel-2019a intel-para/2019a LAMMPS/9Jan2020-cuda"

run_openmp: "srun"
run_mpi: "srun"
